spring.application.name=${BOOKING_APPLICATION_NAME}
server.address=${BOOKING_APPLICATION_ADDRESS}
server.port=${BOOKING_APPLICATION_PORT}
spring.data.redis.host=${BOOKING_DATA_REDIS_HOST}
spring.data.redis.port=${BOOKING_DATA_REDIS_PORT}
spring.data.redis.timeout=2000
spring.data.redis.database=0
spring.cache.type=redis
spring.cache.redis.cache-null-values=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migration=true
spring.flyway.cleanDisabled=false
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

spring.datasource.url=${BOOKING_DATASOURCE_URL}
spring.datasource.username=${BOOKING_DATASOURCE_USERNAME}
spring.datasource.password=${BOOKING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true



topic.ticket-refund=notification.refund
topic.booking=notification.booking
topic.user.mass-mail=user.mass-mail
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}