spring.application.name=booking-service
server.address=localhost
server.port=8082
spring.data.redis.host=${BOOKING_DATA_REDIS_HOST}
spring.data.redis.port=${BOOKING_DATA_REDIS_PORT}
spring.data.redis.timeout=2000
spring.data.redis.database=0
spring.cache.type=redis
spring.cache.redis.cache-null-values=false

spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migration=true
spring.flyway.cleanDisabled=false

spring.datasource.url=${BOOKING_DATASOURCE_URL}
spring.datasource.username=${BOOKING_DATASOURCE_USERNAME}
spring.datasource.password=${BOOKING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true