server:
  port: ${GATEWAY_PORT}
  address: ${GATEWAY_ADDRESS}
spring:
  application:
    name: ${GATEWAY_APPLICATION_NAME:gateway}

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        - id: users-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
          filters:
            - CircuitBreaker=usersCircuitBreaker, forward:/fallback/users

        - id: booking-service
          uri: http://booking-service:8082
          predicates:
            - Path=/booking/**
          filters:
            - CircuitBreaker=bookingCircuitBreaker, forward:/fallback/booking
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
jwt:
  secret: ${JWT_SECRET:your-super-secret-key-at-least-32-characters-long!}
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
app:
  frontend-path: ../frontend/