spring.application.name=user-service
server.address=${USER_APPLICATION_ADDRESS}
server.port=${USER_APPLICATION_PORT}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migration=true
spring.flyway.cleanDisabled=false

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
logging.level.org.springframework.web.servlet.mvc.method=DEBUG
logging.level.com.microservices_example_app.users=TRACE

spring.psw4j.hash.bcrypt.rounds=10
spring.psw4j.hash.bcrypt.minor=b

rate-limit.max-attempts=10
rate-limit.window-seconds=60


spring.datasource.url=${USER_DATASOURCE_URL}
spring.datasource.username=${USER_DATASOURCE_USERNAME}
spring.datasource.password=${USER_DATASOURCE_PASSWORD}
#spring.datasource.url=jdbc:postgresql://localhost:5432/microservices_users
#spring.datasource.username=postgres
#spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
user-service.authentication.reset-password-url=${RESTORE_PASSWORD_URL}
#user-service.authentication.reset-password-url=http://localhost:8080/users/reset-password
spring.kafka.bootstrap-servers=""
topic.authentication=notification.authentication
app.root-admin.username= ${ADMIN_USERNAME}
app.root-admin.email= ${ADMIN_MAIL}
app.root-admin.password= ${ADMIN_PASSWORD}