spring.application.name=user-service
server.address=${USER_APPLICATION_ADDRESS}
server.port=${USER_APPLICATION_PORT}
spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migration=true
spring.flyway.cleanDisabled=false
spring.psw4j.hash.bcrypt.rounds=10
spring.psw4j.hash.bcrypt.minor=b

rate-limit.max-attempts=10
rate-limit.window-seconds=60


spring.datasource.url=${USER_DATASOURCE_URL}
spring.datasource.username=${USER_DATASOURCE_USERNAME}
spring.datasource.password=${USER_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

user-service.authentication.reset-password-url=${RESTORE_PASSWORD_URL}